task1=abc
task2=123
task3=....\.
task4=[cmf]an
task5=[hd]og
task6=[ABC][nop][abc]
task7=waz{3,5}up
task8=aa+b*c+
task9=\d+ files? found\?
task10=\d\.\s+.*
task11=^Mission: successful$
task12=^([^.]*)\.pdf$
task13=(([A-Z][a-z]{2}) (\d{4}))
task14=(\d+)x(\d+)
task15=I love (cats|dogs)
task16=.*
