task17=-?\d+(?:\.\d+)?\b
task18=(\d{3})
task19=^([^+@]+)
task20=<(\w+)
task21=(\w+)\.(?:jpg|png|gif)$
task22=^\s*(.*?)\s*$
task23=at\s+(\w+)\.(\w+)\(([^:]+):(\d+)\)
task24=(\w+)://([^:/]+)(?::(\d+))?
